### ISSUE TITLE
MacBook with m1 can not locate any Comsol installation When use Mph

### ISSUE THREAD

**Issue by drench1** [MPh-py/MPh#143] opened 2023-07-09 06:59 UTC
My M1 chip MacBook encounters an error "RuntimeError: Could not locate any Comsol installation" when calling the Mph library. However, I have already installed Comsol 6.1 and tried adding the address of Comsol 6.1 in the zshrc file, but it still doesn't work.How to fix it?

**Comment by john-hen** [comment] 2023-07-10 10:34
Duplicate of issue #80.

**Closed by john-hen** 2023-07-10 10:34 UTC
