### ISSUE TITLE
`model.evaluate()` doesn't return all data points

### ISSUE THREAD

**Issue by Adrien-Amour** [MPh-py/MPh#142] opened 2023-07-06 18:02 UTC
I'm exporting data from a comsol file to analyse in python using the following line of code,

> (x, y, z, Vol, Px, Py, Pz) = model.evaluate(['x', 'y', 'z', 'meshvol', 'es.Px', 'es.Py', 'es.Pz'])

the issue is that the length of the arrays defined by this command is smaller than the number of finite elements in the model. I know this because I have also exported using the comsol gui and there is about an 800 point discrepency between the number of data elements in each method (there is about 140000 points overall). This results in my analysis producing different results depending on whether i export the data as a text file and analyse that, or if i export the data using model.evaluate. Is there any reason why this might happen/ any way I can fix it?

**Comment by john-hen** [comment] 2023-07-07 08:06
Hi. I don't see a reason why this would happen, but I also cannot reproduce what you are doing. If you think this is a bug (and it could also be in Comsol, rather than MPh), you should think if you can provide a reproducible example, i.e. a model file. Ideally a minimal example, i.e. a simple model, quick to solve, producing little data.

**Comment by john-hen** [comment] 2023-09-06 20:23
Closed as: non-reproducible.

**Closed by john-hen** 2023-09-06 20:23 UTC
Labels: needs info
