### ISSUE TITLE
Running mph in background with nohup crashes upon logging out of ssh session

### ISSUE THREAD

**Issue by Raketenjoint** [MPh-py/MPh#188] opened 2024-08-14 12:49 UTC
I want to run comsol in the background with the  following command, so I can leave the session on the workstation running after detaching my ssh session:
`nohup python3 script.py &`
However it crashes with the following Traceback:
```
less nohup.out
  File "script.py", line 36, in simulation
    model.solve()
  File "/home/XXX/.local/lib/python3.10/site-packages/mph/model.py", line 349, in solve
    node.run()
  File "/home/XXX/.local/lib/python3.10/site-packages/mph/node.py", line 540, in run
    java.run()
java.lang.java.lang.NullPointerException: java.lang.NullPointerException
Error while disconnecting client at session clean-up.
Traceback (most recent call last):
  File "SourceFile", line 290, in com.comsol.model.util.ModelUtil.disconnect
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/XXX/.local/lib/python3.10/site-packages/mph/session.py", line 154, in cleanup
    client.disconnect()
  File "/home/XXX/.local/lib/python3.10/site-packages/mph/client.py", line 439, in disconnect
    self.java.disconnect()
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Tried to disconnect while not connected.
```
I would normally use the following batch command for comsol:
`nohup comsol batch -inputfile <inputfilename> -outputfile <outputfilename> -batchlog <logfilename> -np <number of cores> -study <study tag> l&`
How can we run comsol with mph in the background for long parameter optimizations?
Thank you for this useful implementation while we are waiting for COMSOL LiveLink in python.

**Comment by john-hen** [comment] 2024-08-14 15:53
Hi. Isn't that an issue with `nohup` rather than MPh? After all, it's `nohup` that promises it would "not hang up", and yet it does.

The way I interpret that error message, what happens is this: As you log out, the server process gets killed. MPh starts `comsol mphserver` as a subprocess from the main Python process. After the server suddenly disappeared, the client runs into an undefined condition (understandably). Then the main Python process exits because an exception was raised. At exit we always do some clean-up, such as properly disconnecting the client from the server. In your case that also fails, because the client is already in an undefined state, hence the second exception.

I don't know what to about that. Maybe you want to look into it more. I don't use `nohup`, so no idea how it's supposed to handle subprocesses. But we are doing nothing unusual here, so if `nohup` can't deal with that, then that's probably it.

Most people who run Comsol (with or without MPh) on a remote compute cluster use a job manager such a Slurm. It schedules the job and runs it sometime later, and would even send you an email when the job is done. No need to stay logged in via SSH the whole time.

**Comment by john-hen** [comment] 2024-08-16 07:52
Closed: out of scope.

**Closed by john-hen** 2024-08-16 07:52 UTC

**Comment by Raketenjoint** [comment] 2024-08-26 10:02
Thank you for your fast reply. I could not figure a way out, how to keep the comsol mphserver subprocess running on our linux workstations.

It tried all these approaches:

1. Nohup 
`nohup python3 script.py >/dev/null 2>&1 &`
2. Disowning the process: 
`python3 script.py & 
bg %1 
disown -hr %1`
3. Using terminal multiplexer GNU screen 
`screen -A -m -d -S python3 script.py &` 
4. I went that far to set up slurm on the workstation with the configuration file:
```# slurm.conf file generated by configurator.html.
# Put this file on all nodes of your cluster.
# See the slurm.conf man page for more information.
#
ClusterName=localcluster
SlurmctldHost=localhost
MpiDefault=none
ProctrackType=proctrack/linuxproc
ReturnToService=2
SlurmctldPidFile=/var/run/slurmctld.pid
SlurmctldPort=6817
SlurmdPidFile=/var/run/slurmd.pid
SlurmdPort=6818
SlurmdSpoolDir=/var/lib/slurm/slurmd
SlurmUser=slurm
StateSaveLocation=/var/lib/slurm/slurmctld
SwitchType=switch/none
TaskPlugin=task/none
#
# TIMERS
InactiveLimit=0
KillWait=30
MinJobAge=300
SlurmctldTimeout=120
SlurmdTimeout=300
Waittime=0
# SCHEDULING
SchedulerType=sched/backfill
SelectType=select/cons_tres
SelectTypeParameters=CR_Core
#
#AccountingStoragePort=
AccountingStorageType=accounting_storage/none
JobCompType=jobcomp/none
JobAcctGatherFrequency=30
JobAcctGatherType=jobacct_gather/none
SlurmctldDebug=info
SlurmctldLogFile=/var/log/slurm/slurmctld.log
SlurmdDebug=info
SlurmdLogFile=/var/log/slurm/slurmd.log
#
# COMPUTE NODES
NodeName=localhost CPUs=88 RealMemory=500000 State=UNKNOWN
PartitionName=LocalQ Nodes=ALL Default=YES MaxTime=INFINITE State=UP
`
Running with sbatch the job file:
`#!/bin/bash
#
#SBATCH --job-name=COMSOL
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=88
#SBATCH --mem=100G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err

module load python
python3 script.py
```

All these approaches throw the same error messages in the report.log after logging out:
```2024-08-26 15:15:48,344 - mph - ERROR - Error while disconnecting client at session clean-up.
Traceback (most recent call last):
  File "SourceFile", line 290, in com.comsol.model.util.ModelUtil.disconnect
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/XXXX/.local/lib/python3.10/site-packages/mph/session.py", line 154, in cleanup
    client.disconnect()
  File "/home/XXXX/.local/lib/python3.10/site-packages/mph/client.py", line 439, in disconnect
    self.java.disconnect()
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Tried to disconnect while not connected.
2024-08-26 15:15:48,345 - mph - INFO - Exiting the Java virtual machine.```
I'll just hope that maybe someone with more knowledge on Linux/Python Subprocesses/COMSOL/Jpype might look by some day. In the meantime, I will have to start the scripts locally.

**Comment by Raketenjoint** [comment] 2024-08-27 04:31
Thanks John for your records. All scripts and simulation work fine as long as I stay logged on to the workstation:
```
COMSOL Multiphysics 6.2.0.339

Python 3.10.12
MPh version: 1.2.4
Starting Comsol client.
Loading demo model from the Tutorial.
Solving model.
Evaluating results.
C = 0.737 pF
```
As soon as I `logout`, the mphserver/Java virtual machine are terminated though:
```
Traceback (most recent call last):
  File "SourceFile", line 212, in com.comsol.clientapi.impl.StudyClient.run
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/hdd2/xxxx/COMSOL/2024-08-13_Beam_Steering_Global_Optimization/slurm_test/demo.py", line 13, in <module>
    model.solve()
  File "/home/xxxx/.local/lib/python3.10/site-packages/mph/model.py", line 349, in solve
    node.run()
  File "/home/xxxx/.local/lib/python3.10/site-packages/mph/node.py", line 540, in run
    java.run()
java.lang.java.lang.NullPointerException: java.lang.NullPointerException
Error while disconnecting client at session clean-up.
Traceback (most recent call last):
  File "SourceFile", line 290, in com.comsol.model.util.ModelUtil.disconnect
Exception: Java Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/xxxx/.local/lib/python3.10/site-packages/mph/session.py", line 154, in cleanup
    client.disconnect()
  File "/home/xxxx/.local/lib/python3.10/site-packages/mph/client.py", line 439, in disconnect
    self.java.disconnect()
java.lang.java.lang.IllegalStateException: java.lang.IllegalStateException: Tried to disconnect while not connected.```
```
I only added a loop to the python script to give enough time for logging out:
```python
import mph

print(f'MPh version: {mph.__version__}')

print('Starting Comsol client.')
client = mph.start()

print('Loading demo model from the Tutorial.')
model = client.load('capacitor.mph')

for i in range(10):
        print(f'Solving model #{i}.')
        model.solve()

        print('Evaluating results.')
        C = model.evaluate('2*es.intWe/U^2', 'pF')
        print(f'C = {C:.3f} pF')
```
Could you check whether the batch job continues running after you logout from the machine? Thank you.

**Comment by john-hen** [comment] 2024-08-27 14:36
I already did that yesterday, log out after submitting, as mentioned. But I double-checked just now with the longer job (queued for 7 seconds, ran for 1:26 minutes) and made extra sure by submitting it as `sbatch job && exit`.

It's not that. I would say "unsurprinsingly so" if it weren't for the, in my eyes, inexplicable experience you report here. After all, the jobs are started from the Slurm "daemon". So by (obvious) design it is not a log-in shell and by virtue of being a daemon stays resident indefinitely. Then the same should (must, actually) apply to its subprocesses.

In case it's not clear, please note that "Python subprocesses" are no different from any other processes. The Python `subprocess` module is just a wrapper around the C API provided by the operating system. It creates a new process that inherits the environment from its parent process. When we run the Comsol server via MPh, its parent process is the Python process. When you run it directly from the terminal, its parent process is the log-in shell, typically Bash. With Slurm, the parent process is the Slurm daemon (though it also sets your user id when it spawns the subprocess). The operating system does not care if any of the processes involved are running Python or a Java VM or whatever.

If anything, the OS only cares about the process hierarchy, in that it kills all child processes (and grandchildren, etc.) when you log out. Which, by the way, is also by design. Linux/Unix does that. Windows (when using a Remote Desktop connection) would just leave them running. Obviously there's nothing an application can do when the operating system is intent on killing it.

The mystery then is why your OS does that. I really don't see how anything on the application side of things (Python, MPh, JPype, Comsol) would suddenly error out just when you log off. The only way the application even knows about it is via some system "signal" issued by the OS. Unless maybe some other resource is pulled out from under it. The only thing that comes to mind would be the network socket that faciliates the communication between Comsol client and server. But I don't see a reason for that either, since it's a local loopback anyway.

Also note that, according to the [download stats], MPh is overwhelmingly deployed on Linux. I don't know who that is, but given that the primary user base is probably on Windows, I'd be surprised if the downloads weren't driven by some compute cluster somewhere in the world, and thus running Slurm or some other job manager. Not to mention that I've run the test suite many times myself before, with Slurm as well as LSF. Plus I know for a fact that people are using MPh on that same cluster routinely. Your experience is definitely an outlier.

If I were you, I'd test Slurm with a job that just has a Bash subprocess sleep for like a minute. Then again, I would not know what conclusion to draw from either outcome.

[download stats]: https://pypistats.org/packages/mph

**Comment by Raketenjoint** [comment] 2024-08-28 06:48
Wow, thanks for your detailed explanations. I reduced the complexity of the example to submitting a simple bash script `sbatch timer_job.sh`, which prints the time every 5 s for 100 repetitions:
```bash
#!/bin/bash
#
#SBATCH --job-name=timer
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=88
#SBATCH --mem-per-cpu=1G
#SBATCH --output=%x_%j.out
#SBATCH --error=%x_%j.err
#SBATCH --mail-type="all"

for i in {1..100}
do
    echo $i
    date
    sleep 5s
done
```
It does not terminate when logging in and out of the ssh shell. I will test some subprocesses next.
I also expected that the slurm daemon should start the script, but comsol runs under my username instead of slurm (as you said it sets my user-id when it spawns processes).
I might have not fully configured slurm yet and check further for a minimum working example. Our few workstations did not use job schedulers so far.

**Comment by john-hen** [comment] 2024-08-28 17:39
> My MWE might use different settings than subprocesses in mph though.

Not really, that's pretty much what we're doing:
https://github.com/MPh-py/MPh/blob/42549fecff80c490e5fc42ac6f63b2843b88a817/mph/server.py#L108

Except that `start` is an alias for [`subprocess.Popen`](https://docs.python.org/3/library/subprocess.html#subprocess.Popen) and `command` is `comsol mphserver` etc. We use `Popen()` instead of `subprocess.run()` because we don't want that call to block (i.e. have the server run in the background). And as your example shows, it's not a problem with "dangling pipes" for `stderr` etc., since you're redirecting none of them.

You are using a Floating Network license, right? Just asking because on Windows, for single-CPU licenses, Comsol has some sneaky ways of detecting that the user is connected via Remote Desktop and then deliberately refuses to run. Not sure if they're doing stuff like that on Linux as well.
